# (PART\*) Some Preliminaries {-}

# The Examined Life

```{block, type="epigraph"}
...the unexamined life is not worth living.\
---Socrates
```

`r newthought("Human beings")` are endowed with a unique capacity, the ability to reflect on what we believe and do. Unlike other animals, we are capable of taking a distance from the evidence of our senses and asking ourselves, "Should I trust what I see or not?" Likewise in the realm of desire and action:  we can examine our own desires, intentions and plans and ask ourselves, "Should I act on these or not?" In both cases we are capable of stepping back from the immediate demands of our situation and seeking orientation from another source - we seek *reasons* to believe or doubt what we see and *reasons* to follow or resist our urges. This reflective capacity is the source of our strength since it has enabled us to both understand and manipulate the world around us like no other creature on the planet. But it also puts us in the uniquely awkward position of having to justify ourselves to our own worst critics, ourselves. 

Shakespeare's tragic figure of Hamlet sums this up quite well when he on the one hand proclaims,

> What a piece of work is a man! how noble in reason! how infinite in faculties! in form and moving how express and admirable! in action how like an angel! in apprehension how like a god! the beauty of the world, the paragon of animals!

And yet he himself is incapable of overcoming his own inability to act, paralyzed as he is by self-doubt and uncertainty, as the quotation above continues, 

> And yet to me what is this quintessence of dust?[@shakespeareHamlet1985]

The capacity to reflect is the source of both our godlike "apprehension" and the difficulties we inevitably encounter in figuring out what we should do. Even though, thankfully, most of us do not experience the tension between these two aspects of our ability to reflect on ourselves and our circumstances quite as dramatically as Hamlet did, all of us face this essentially human predicament. As we will be seeing in this text, philosophical ethics is another, much less bloody, way of exploring this predicament. To set the stage for what we will be up to here I want to first say a bit more about our unique reflective capacity and our ability to pay attention to reasons. Then I'll turn to a more detailed account of what is distinctive about philosophy in general and philosophical ethics in particular.

## What do I know?

`r newthought("To start")` I don't want to exaggerate too much our differences from the other organisms with which we share the planet, since we do share quite a bit with them. We may be, as Aristotle's definition of human beings has it, "rational animals," but we are still animals, and like all other animals with nervous systems we can do two things. We can perceive what is happening around us and we can respond to it in real time. Animal nervous systems are the product of hundreds of millions of years of evolution, and extremely useful for helping animals survive and flourish in a complex and constantly changing environment. What is distinctive about the human nervous system is the degree to which the constant stream of information coming into it through our senses is integrated and organized. It is integrated in an experience which is, as far as we can tell, more fully conscious than in other creatures. And it is organized more explicitly, as is especially evident in our ability to use language.

And likewise with the equally constant stream of information produced by our nervous systems, controlling our bodily and verbal responses and the way these both in turn feed back on our thought processes. That these are capable of being integrated and organized in ways that are unique to human is clearly demonstrated in the astonishing variety and complexity of human cultural and social forms. Of course animals out-perform humans in a variety of specialized tasks, but human acheivements in the worlds of culture and society are seemingly capable of infinite variation and complexity ranging from Simone Biles to the internet, from the modern corporation to Tuvan thraot singing.

Above all it is our capacity for language use that makes possible the intergration and organizational flexibility of the human mind. 

First of all, our ability to use and understand language enables us to explicitly categorize and classify what we experience - things are not just there in our surroundings as objects we happen to come across. Instead we both consciously and unconsciously organize the things we encounter into groups based on concepts such as: edible or inedible, animate or inanimate, threatening or safe, members of our social group or not members of our group, male or female, cause or effect, and so on. Now although there is clear evidence that certain animals do this to a limited extent as well - dogs, for example distinguish between their owners and strangers quite readily and reliably - for us, these acts of categorizing and classifying can be endlessly expanded and modified and also made fully explicit to our own awareness. We can endlessly expand our categories to include anything and everything conceivable - "80's hair bands," "things not good for eating in bed," "mops," and "former presidents," just to give a quick random sample. 

Not only do we thus have an infinitely variable way of looking at the world and organizing our experience according to concepts and categories, but we can see and understand how we are doing so by reflecting on it an talking about it. We can make it explicit how our experience of things is organized and maybe even do it in a different way. We can add new categories or modify how we use them as we notice new similarities or subtle distinctions among things. We may also revise and refine our categories as accumulated personal and shared experience reveals to us their strengths and weaknesses - whether they "carve nature at its joints" or not. This ability to look at things in new ways as a result of collectively accumulated experience is rooted in the fact that we use language to do so and language is both infinitely extensible and essentially shared with other humans.  Most importantly for the story I am telling here, we can ask ourselves about the implications of the way we look at the world, and we can wonder about whether we *really* have good reasons for looking at things as we do. 

This is a point that it is hard to overemphasize but also easy to miss since we take it so much for granted. By asking ourselves about the reasons we have for believing that some aspect or other of our experience is true we are asking ourselves not only about the way things are, but about the way things *should* be; not just what we happen to believe about things based on their appearance to us, but about what we *should* believe about them because it reflects their true reality.  And by asking ourselves such questions we are asking what philosophers call normative questions, questions that have to do with values, with concepts like right, wrong, good, bad, true, false, beautiful and ugly. 

## What should I do?

`r newthought("Thus")` far I have been emphasizing the role of reflection and the seeking of reasons in our attempts to understand the world in which we live. But this of course is an incomplete picture, since we are not just disembodied minds looking at and trying to figure out the world. We are embodied, social beings who feel and act on needs and impulses, experience emotions, form and try to realize intentions, coordinate or compete with others, and seek or shun each others' company. This practical side of human life is, just as we have seen for our experiential selves, equally capable of being made explicit and becoming an object of our reflective capacities. We don't have to simply act on whatever urges happen to come to our attention, we can stop and think about what to do instead. Hence we find ourselves presented with choices - should I follow my immediate urges, or should I refrain from doing so in order to realize other goals? Once again, just as in the case of belief, our reflective capacity introduces a normative dimension to human life as we come to ask ourselves questions about our own needs, desires and decisions. We wonder what we should do in some particular situation, perhaps when our feelings are telling us one thing and our experience is reminding us of the bad results the last time we acted on similar impulses. And this generalizes as well, as we come to reflect on our motivations as such, on which of our goals are more worth pursuing in the long run, on the nature of human motivation and goals in general, on what might truly be the best way to live our lives. And thus philosophical ethics is born as a product of reflection on our own decision making as potentially thoughtful social animals. 

## Philosophical Ethics

`r newthought("Philosophical")` ethics is nothing but the deliberate pursuit and clarification of this kind of reflection on our own values, actions and decisions. Even though, as I have been emphasizing, we all have the capacity to reflect on our lives and choices, we do not always spend the time or make the effort to do this carefully and deeply. This is because we are mostly preoccupied with the practical details of our own lives. We are too busy living to take the time to stop and think about the significance of what we are doing. However, at times in the lives of both individuals and societies the need to reflect more clearly on what we are doing becomes more of an imperative. For individuals the need to stop and think and to reconsider the basic assumptions on which we act often arises in relation to important life events or radical changes - the sudden loss of a loved one; the birth of a child; living  through a natural disaster or a war; or even the transition to adulthood in which one assumes full moral and legal responsibility while also gaining the full rights and privileges accorded to adults. These are topics and situations, as we will see later, that are often the focus of discussions in the branch of philosophical ethics called applied ethics. In the case of societies, philosophical thinking in general and philosophical ethics in particular likewise flourish in times of great stress or change - for example when radically different societies suddenly make contact with each other; when new groups and ways of living displace old groups and ways; when new discoveries challenge peoples' basic views of the nature of things; when societies find their very existence threatened by seemingly insurmountable obstacles. In cases like these it becomes imperative to reflect more carefully on what we assume is of value to us individually and as a society, on what counts as a good life. 

A philosophical approach to ethics, or moral philosophy, is concerned with a number of different sorts of questions. Thus the broader field of ethics can be divided up into a number of different regions or areas of concern. Some of the main questions and their corresponding sub-fields are:

``` {marginfigure}
**Descriptive ethics**: what do people really think about right and wrong?
``` 

- What ethical views do real people have? This is the concern of **descriptive ethics**, which tries to figure out what beliefs people happen to actually have concerning ethical questions. As such, descriptive ethics is not exclusively a philosophical approach to ethics in that sociologists, psychologists, anthropologists and other social scientists are also concerned with people's ethical beliefs in this sense.

``` {marginfigure}
**Meta-ethics**: how does thinking about ethics work?
```

- What is the nature of ethical thinking and ethical concepts? This is usually referred to as **meta-ethics**, which refers to a higher-order or "meta-level" discussion about ethical modes of thinking. Here again, philosophers as well as social scientists often ask meta-ethical questions in their attempts to understand what is distinctive about ethical thinking as opposed to other modes of cognition.

``` {marginfigure}
**Prescriptive ethics**: what is really the right thing to do?
```

- What ethical principles or decision-making procedures are really justified? This is the basic question addressed by normative or **prescriptive ethics**, which is the uniquely philosophical attempt to find the true basis of ethical thinking. Much of our discussion in the first half of this text falls under this heading since we will be examining various attempts to give an account of the basis and justification of ethical thought, belief and action.

``` {marginfigure}
**Applied ethics**: what is the right thing to do in this real-world case?
```

- How does all of this play out in real life cases? This is the concern of **applied ethics**. Under this heading are also to be found discussions of ethical issues associated with some particular area of human life, profession, or subject matter - hence medical ethics, business ethics, legal ethics, environmental ethics, bioethics and so on are sub-fields within applied ethics.

We should keep in mind as we proceed that these various regions are not always so clearly separate from one another. Our description of what people believe about ethical questions, for example, is clearly often informed by what we think they are justified in believing. Nevertheless we should keep in mind the fact that we can look at ethics from each of these different points of view and recognize that failing to do so may result in unnecessary confusion.

In conclusion we might say that philosophical ethics involves deliberately reflecting on our ideas about ethics in general and on specific applications of these ideas to actual cases and controversies. Another term for such deliberate reflection is "critical thinking." This should not be looked at as a primarily negative activity as the word "critical" might suggest, but as the positive attempt to arrive at the truth of the matter by thinking carefully about what are often complex and ambiguous ideas and concepts. Even though, as I mentioned at the outset, all of us are equally capable of reflecting critically on our own beliefs, desires, actions and values, it does take some effort and quite a bit of practice to be able to do so effectively. This is because critical thinking is a skill like anything else that we might do with our minds (like solve algebra problems or identify different species of trees) and we shouldn't expect to be experts at it from the start. In the next chapter we will look at and get some practice using one of the most important tools for critical thinking - the logical analysis of arguments.




