# (PART\*) Approaching Ethics {-}

# Relativism

**_Opinion_**, this seems to be where ethics starts and in many people's minds where it ends. You have a right to your opinion about right and wrong and I have a right to mine, so let's just leave it at that. Given what we have been looking at so far, not to mention all of the unread pages still ahead, it is probably already apparent that that is not going to be the whole story about ethics. It is nevertheless a deeply rooted assumption that ethical claims *must be* opinions, since they are clearly **not** factual claims and that seems to be the only other sort of claim we can possibly be making when we are using language to state things. That this assumption does not in fact hold up to closer inspection is what this chapter is going to argue. Before we get to that argument, however, I would like to say a few words about what we are going to be up to in the next few chapters that make up this part of the text.

**_In this part_** of the text we consider a variety of approaches to ethics. We'll start out from the approach that claims that ethics is just a matter of opinion. This is known as relativism and, in spite of its flaws as an account of ethics, it remains popular. Next we will look at two different variants of a claim that seems to be diametrically opposed to relativism -- the claim that ethics can and should be based on religion. And finally, we will examine a view that itself seems to swing back in some other direction, which again seems diametrically opposed to the attempt to root ethics in religion. This is known as egoism and it claims that ethics is psychologically or politically a dangerous and mistaken idea. In spite of the differences of these approaches, they do however share something in common, namely, the idea that if ethics is to make any sense at all our talk about ethics has to be translated into talk about something else like culture, or religion or psychology. As we will see none of the approaches we examine in this part of the text are ultimately adequate -- they all fail to capture what is distinctive about ethics and why ethical norms demand our attention. Thus in the third part of the text we will explore a range of philosophical attempts to reconstruct ethics on its own terms, to make explicit the basis for ethics as an independent source of norms.

## Claims and Consequences of Moral Relativism

```{block type='epigraph'}
 If anyone, no matter who, were given the opportunity of choosing from amongst all the nations in the world the set of beliefs which he thought best, he would inevitably -- after careful considerations of their relative merits -- choose that of his own country. Everyone without exception believes his own native customs, and the religion he was brought up in, to be the best.
 
---Herodotus, The Histories
```


**_One of the_** most obvious facts to any casual observer of human behavior is its enormous diversity. People live in almost any conceivable physical environment, from dense tropical jungles, to frozen polar deserts, from small villages with thatched huts to modern industrial cities made of concrete, steel and glass. In addition, our cultural practices and norms reveal perhaps an even greater diversity. Some human cultures place value on devotion to the group at the expense of individual liberty, others emphasize the unique individual while downplaying our relation with others. Some cultures value continuity and tradition (think of the Amish of Central Pennsylvania) while others value innovation and rapid change (think of the Japanese fascination with technological innovation, for example the development of humanoid robot companions for older people). Some cultures value constant productive work while others place far more emphasis on living well and enjoying social interaction with others. Some cultures allow men and women to participate equally in all areas of social life, while others have entirely separate spheres for the two sexes. Recognition of this diversity is what has led some philosophers and social scientists to formulate a theory known as "cultural relativism," which takes these casual observations and turns them into an explicit set of claims about the nature of value judgments. This theory is not only a popular theory about the nature of values. It also presents a challenge to the whole enterprise of philosophical ethics since it leads to the view that rational discussion and argument have little role to play in ethical decision making. Ethical decisions, opinions and judgments, according to cultural relativism, are always relative to the cultural environment within which they are made.

**_Cultural relativism_** is one particular variant of a broader position that we can call moral relativism. Another variant is "subjective relativism" which appeals to individual feelings as the basis of moral judgment. Cultural relativism boils down to a few simple and seemingly obvious claims:

```{block type='rmdnote'}
**According to relativism**

- Ethical or moral claims are not objective in the way factual claims are.
- There is no neutral standard for determining right or wrong.
- All value judgments are relative to our personal or cultural perspective.
```

### A first case for relativism{-}

**_At first_** this set of claims may seem obviously true. After all, given the diversity of human values and customs, how could there be anything more than relative standards, standards that are only applicable within a given culture? Many people find relativism intuitively appealing and might even offer as a preliminary case for relativism the following points:

- *Cultural diversity*: Human culture has always been extremely diverse. And many people seem to have equally diverse views on what sort of behavior is acceptable. It seems to follow from this that there cannot possibly be any standards for deciding between these views.
- *How we learn about values*: It seems obvious that we learn about values, and come to accept the values that we do because these are the values that are shared by the people who raise us. They are the values of our families and communities.
- *Intolerance*: There have been plenty of cases throughout history in which one group of people firmly believed that their values were not just acceptable for them but absolutely right, and used this as a justification for committing atrocities against other people. Relativists insist that the only way to avoid this kind of intolerance is to accept that there are no ultimate standards.

### What is at stake{-}

**_In a moment_** we will consider each of these points in greater detail. Before we do this it will be helpful to spell out what is at stake here. That is, we should consider what would be the case about ethical principles and decision making if cultural relativism were true. Its defenders make much of the positive consequences of this theory, while its opponents emphasize its negative implications. As we consider these consequences of the theory we must remember that whether or not we like where a theory leads us, in terms of its theoretical consequences, cannot itself determine whether the theory itself is correct. Reality does not care whether or not we like it. In the case of relativism at least, the extreme nature of its consequences helps explain why it is such a controversial theory.

**_Defenders of relativism_** present it as the best way to acknowledge the great variety of human value systems and cultures. If there are no ultimately correct moral principles, then all human cultures become equally valid as ways of life, at least for different groups of people. This seems to encourage tolerance of other ways, a welcome relief after millennia of people intolerantly fighting with each other over their different views. After all, if there are no ultimate standards for right and wrong, we would could never justifiably say, "Your group is wrong in doing what you do and so we have the right to force you to change your ways." On the other hand, a relativist cannot really consistently promote tolerance -- otherwise she would be granting tolerance for other cultural practices the status of a universal value, valid for everyone and this is what relativism says does not exist. So we should really say that relativism really only rules out one possible way of dealing with conflicts: the rational settlement of differences with reference to some kind of universal principles or values. Sometimes differences of opinions might be tolerated by the members of the groups that differ, sometimes one group will attempt to push its values on the other group. Both approaches are consistent with the claims of relativism.

**_The first_** troubling consequence of relativism is one you may already have suspected: if there are no real standards, standards about right and wrong that are independent of cultural perspectives, it doesn't seem possible to condemn other cultures or individuals for doing awful things. For example, imagine that there is a society that has two major groups of people. One of these groups, who happen to be the majority of the population, decides that the other group doesn't deserve any respect, perhaps even that they are somehow naturally deficient or inferior. As a result they perform painful and often fatal experiments on the minority group, force them to work without pay, and even decide just to kill them off because it makes them feel better about themselves. What would a relativist say about this? It seems that since the relativist is only willing to recognize local or relative standards, she would have to conclude that although she doesn't like it, or that such behavior would never be tolerated in her society, she really can't condemn what this group of people are doing as simply being wrong. Why not? Well, because it seems right to the majority of people in that other society.

**_Furthermore_**, relativism, if it were true, would require us to reject the idea that we can really make moral progress. Consider voting rights for women and African-Americans. In early American history both groups were denied these rights. Later on, after the Civil war in the case of African-American men and then in the early twentieth century in the case of all women, the Constitution was amended when people recognized that it was wrong to restrict these groups' access to the political process just because of race or gender. Many of us would consider this a case of moral progress -- a basic right was extended to people who had previously, for no good reason, been denied this right. What would a relativist say? Could they say that this was really a case of progress? Probably not, since progress implies that things are getting better, and this requires that there is some standard against which we can measure better or worse. So, for the relativist there is no progress, only different ways of doing things, none of which are really better or worse than any others. Is this a conclusion you are comfortable with?

**_Relativism seems_** like a plausible theory about the nature of value judgments. It also seems, at first glance at least, to be a theory with nothing but positive implications -- it seems to encourage of diversity and lets everyone do their own thing. However, as we have just seen this easy-going character of relativism soon reveals a darker side. A relativist cannot really have any grounds for condemning any behavior at all, no matter how intuitively awful it seems, as long as someone believes that it is OK. In addition relativism does away with one of the most important parts of our moral thinking, the idea that maybe through our efforts we can make things a little better. This idea of progress is rendered simply meaningless by relativism. These implications of relativism do not by themselves let us know whether or not relativism is true. At best they reveal what the stakes are -- if relativism is true we get tolerance at the expense of having to tolerate anything all at that someone feels is the right thing to do. To determine whether or not relativism is true we need to consider more explicitly the arguments in support of this theory.

## Defending Relativism

**_Thus far_** we have been looking at the pros and cons of accepting relativism as an approach to ethics. In doing so we have been avoiding asking a simple question, that we now cannot any longer avoid -- *is relativism true?* To answer this question we need to take a look at how we might argue for relativism instead of just leaving it as one opinion among others that we might take or leave. Although it may seem obvious to many people that relativism is in fact true, our examination of the explicit case that can be made in defense of relativism will show that it is not in fact based on very good arguments. But I am getting ahead of the story... 

### Cultural differences {-}

**_The first_** and most obvious way to defend relativism is based on the recognition of human cultural diversity. This was what motivated Herodotus to pronounce that "custon is the kinf of all," and that has led many athropologists and sociologists to embrace it as well. So the first argument for relativism that we will examine here rests on recognition of the diversity of value judgments and tries to argue from this premise directly to the conclusion that there are no ultimate standards for right and wrong.

```{block type='argument'}
We all have different views about right and wrong.

***

Thus there are no standards about what is really right or wrong.
```


**_This argument_** may seem to be persuasive. Doesn't the fact of human diversity automatically entail relativism? But the question we should ask about this argument is not "Does it seem persuasive?", but "Is it valid and sound?" Remember a valid argument is one in which if the premises are true the conclusion must be true. So is this valid? How can we tell? We just ask, "If the premise were true, would the conclusion also have to be true?" In this case the premise seems obviously true, but does that by itself force us to accept the conclusion? Clearly not, since even if the premise is true and we do all disagree, this alone does not have to mean that there are no standards. However implausible it may seem that there are universal moral standards, the fact of human disagreement about what those standards might look like is just not enough to rule out the existence of standards. To see this, it may help to consider a clearly bad argument of exactly the same logical form in which the premise is clearly true and the conclusion is clearly false.

### A counterexample{-}

```{block type='rmdwarning'}
We all have different views about how to deal with stop signs -- some of come to a complete stop while others only slow down.

***

Thus there are no standards regarding stop signs.
```


**_The premise_** in this argument is clearly true as any casual observation of drivers at intersections will show. Yet the conclusion is also clearly false, since there really is a correct way to deal with stop signs, the one written in the relevant section of the laws governing driving. What this shows about the argument from cultural differences is that disagreement alone is not enough evidence for the conclusion that there are no real standards. From the fact that we may disagree about some topic we cannot conclude anything about whether or not any of us are really right or really wrong. We need much more evidence than this to support the conclusions of relativism. We disagree about many things. In some of these cases there is a way of settling disagreements -- look up the law, check the facts if we disagree about the temperature outside or whether or not it is still snowing. In other cases, there is simply no way to settle differences – some people will just not be convinced that the Backstreet Boys or horrible musicians, or that sushi is the best dish on the planet. Likewise in all matters of style and taste.

**_So this argument_** for relativism is inconclusive. Relativism focuses on our differences of opinion and tries to draw from this a conclusion that just does not follow. We still are no closer to deciding whether, as in cases of dispute about the law, we will be able to settle our ethical differences, or whether, as in cases of dispute about taste, we will not. It remains an open question whether or not there are standards in ethics.

### learning right from wrong {-}

```{block type='argument'}
If we get our values from our cultural environments then our values are culturally determined.\

If values are culturally determined then they are relative to cultures.\

We do in fact get our values from our cultural environments.

***

Thus relativism is true -- values are relative to cultures.
```

**_This is a valid argument_**, so at first it seems like the relativist position might be stronger than we have be claiming. The question then becomes whether or not it is sound. Are the premises in fact true? The key premises are the first and the third. Let us consider the first: "If we get our values from our cultural environments then our values are culturally determined." There are two ways we might understand this statement one of which makes it true by definition and the other of which makes it just plain false. If getting our values from our cultural environments means the same thing as our values being culturally determined, then the first premise is true, but completely uninformative, since it gives us no new information. But if, on the other hand, this claim is not true by definition it is in fact false, since it just does not follow that where we get something in any way determines what that thing is. As a counterexample: just because we learn arithmetic within the particular cultural environment of modern school systems does not mean that the content of arithmetic is at all determined by this environment. 2 + 2 = 4 wherever you happen to learn this. What we learn is at least in principle independent of where we learn it.

**_The third premise_**, "We do in fact get our values from our cultural environments," is equally suspect. It is possible that this is true, but it assumes some things about human psychological development that are simply unknown at this point in time -- the extent to which the ideas that we have in our heads are products of our immediate environments, and the extent to which they are products of built in psychological capacities and functions. Well then, where would ideas about right and wrong they come from, if not from the environment in which a person is raised? One possibility is that human moral development is somewhat built in, that we are all born with the capacity for social interaction and that this gets switched on, in a sense, as we grow and interact with others. If this view were correct we would expect to find that the variation of moral ideas among is humans is less pronounced than relativism claims. And in fact, if we ignore the surface differences between human value systems and look at the core values people accept, they start to look very similar.

**_In fact_** we could take this point further and point out that all human cultures share certain basic values. We all:

- honor the dead with some sort of funeral rites and find it incredibly offensive to mistreat the dead.
- act so as to help the group to survive.
 - believe in the importance of telling the truth in general, even if exceptions are sometimes made to this.
distinguish between acceptable and wrongful killing of other human beings.

### Saying different things

**_Relativism isn't quite finshed_** yet though, since there is another popular argument in its favor that we haven't yet considered. This argument appeals to the, once again seemingly obvious, difficulty in coming to any kind of agreement about the meaning of basic moral terms.

## Questioning relativsm

**_The possibility_** that there is a common moral ground between groups of people is tempting as a possible alternative to relativism. What relativism gets right is the fact that we all disagree about how to carry out the basic moral demands these core values impose on us. But what it gets wrong is the degree to which we do all disagree. After all, we all have some way of honoring the dead, we all think that the survival of our group is important, we all recognize that communication is only possible against a general background of truth-telling, and we all agree that there is something that should be considered the wrongful killing of a human being or murder, even if different cultures have very different ways of putting these values into practice.


```{block type='rmdcaution'}
**_But then_**, wait a moment, doesn't relativism just reappear on another level? So what if we all agree on the importance of honoring the dead? Our different views about how exactly to do this have the potential to lead to serious conflict. And it is far from clear that this kind of conflict, conflict about the implementation of core values, can really be resolved.
```

**_In response_** to this problem let us take a closer look at what I claimed above was one of the common core values all human cultures share, the distinction we all make between acceptable and wrongful homicide. The relativist might argue that the fact that we all agree that there is such a distinction in all societies does nothing to alleviate the conflicts between societies. Take the way in which this value was put into practice in Nazi Germany: it was considered wrong to kill a member of the "Aryan" race, but acceptable and even necessary to kill Jews, Slavic people and Gypsies (among others). We, on the other hand, fought against Germany in WWII because, among other reasons, we disagreed that this was a legitimate way to make the distinction between acceptable and wrongful homicide. Our beliefs are that it is only acceptable to kill others in self-defense, in a just war or, in some cases, as a penalty for very serious crimes. Is there any way to resolve this conflict, or does relativism gain back all of the ground it has lost in the preceding discussion?

**_Once we recognize_** that even Nazis are not living in a completely foreign moral universe, that they share with us the basic idea that there is an important moral distinction between justified and unjustified homicide, we can take a critical look at their way of making this distinction. And in fact it is quickly apparent that they made this distinction in a faulty way – based on pseudo-scientific theories of race, based on the political manipulation of people's fears and based on paranoia. Hence, even on their own terms, the way in which they made this important distinction fails to be satisfactory. It is the fact that we share this basic distinction with them that enables us to criticize their way of putting in into practice. We can always ask of a given cultural practice or value, whether it is based on claims that stand up to scrutiny and whether it performs as advertised. This sort of internal criticism is only possible on the basis of shared human concerns that transcend different cultures.



## Further exploration {-}

```{block type='rmdslides'}

Soon there will be a link here to the slideshow summary covering the main points of this chapter.

```

**_Relativism is_** a challenging position to take about ethics. It challenges its defenders to come up with an argument in favor of it that doesn't either [beg the question](#begging-the-question), or undermine itself. 

```{block type='rmdquestion'}
Can a relativist ever lay claim to being correct about anything including the correctness of relativsm? In case she did, then anyone else could simply say, "well relativism may be true for you, but it's not true for me!

```

It is also challenging to its opponents since it seems to fit in well with the intractability of ethical stances. People **do** tend to dig in and refuse to either accept reasons against their own favored views or even the possibility of compromise.







