# Appendix 1: Using Hypothes.is {- #appendix-1}

#### 1. What is it? {-}

It's an online annotation tool. It lets you take notes in the margins of any web page, highlight text, and make page notes which are comments on the whole page. You can in some cases also view and respond to other people's comments. 

- These notes are yours.

- They can be made public so that any other user of Hypothes.is can see them and respond to them.

- They can be private so only you can see them.

- They can be shared with a group so that only members of that group can see or respond to them.

- They can (and should) be organized by key words (tags) so that you can keep track of all of your notes and pages you have taken notes on for research, or just for personal use.

- You can use it for your other classes too. All of your notes will be available for you to see organized by tags, pages and groups on the Hypothes.is site.

#### 2. Pretty awesome huh? What's the catch?  {-}

There is none. Hypothes.is is run by a non-profit on a mission to encourage note taking and discussion on the web. They are most likely people who read books and write stuff in the margins. You know the type. You don't want to buy used books from them.

This is not a tool for collecting data about you and selling it to advertisers -- they respect privacy and you can read the Hypothes.is privacy policy here. It is free. This system is supported by grants and by institutions that sign up for paid versions for their own uses. It is free for use by educators and students. 
 You do need to register, but all you need to sign up is an email addresss. 

Please read the privacy policy, terms of service and community guidelines for more information.

#### 3. How to use it. {-}

Some websites, like this one have it built in. You may have noticed the funny icons in the upper right corner of the pages of this book. If you click the arrow the Hypothes.is tool slides out.

- There is also a Chrome extension for those of you using the Chrome browser. If you install this you'll open it by clicking on a symbol on the top bar of your browser.

- Finally there is a special kind of bookmark called a "bookmarklet" that you can save for use in your browser. That creates a link that you can just click  anytime you want to take notes on a page you are reading. If you don't use Chrome this will be what you want. 

- **NOTE:** since most pages don't have Hypothes.is built in you'll have to use one of these last two methods to use it on other websites.


:::{.rmdnote data-latex="" .infobox}

**Special note for using on a phone:**  Except for when commenting on websites like this that have the Hypothes.is tool built in, you have to do things a little different on a phone. All you have to do is copy the web address of the page you want to annotate and then [go to this page](https://via.hypothes.is/) and paste it in the box. That runs the page through the Hypothes.is server and let's you add your own notes.

:::

#### 4. Getting started {-}

- Go to the Hypothes.is [Start Here page](https://web.hypothes.is/start/) and follow the instructions.

- You'll have to register and either get the Chrome extension or save the bookmarklet. It's simple.

- Then you can join the private group Ethics\@PCT and add a note to this page. To join, follow the link posted on the welcome announcement on the course website.


#### 5. Annotate this page {-}

Your first assignment is to add a group note to this page that will be visible only to the Ethics\@PCT group.

- You can just open the Hypothes.is tool, login and figure it out.

- Or you can follow these detailed instructions...


**_Step one, login:_** Click the arrow to open up the annotation tool, then "login." Enter your ID (most likely your email address) and password. If you haven't registered yet go to the [start Here page](https://web.hypothes.is/start/), follow the instructions then come back to this step.


**_Step two,  pick the right group:_** On the top edge of the tool click the drop-down menu that says "Public" and then switch that to the Ethics\@PCT group. (You can organize your other annotations for other classes by creating a new private group with only you as a member and post to that group.) If you ever mistakenly post something as "public" you can always change it later. You can also edit notes already published.


**_Step three,  highlight some text:_** Use your mouse or touch screen to select some text by clicking and dragging over it. If Hypothes.is is active you'll see the text highlighted in blue with two choices below, "annotate" and "highlight." Select "annotate" and the sidebar will come out with a box for typing in your note. 


**_Step four, write a note:_** Write what you want, but do recognize that all of us in this course will be able to read it. Please write in complete sentences and write clearly! You can even add images or videos to your annotations.


**_Step five, add the tag "assignment one":_** To complete this assignment, you'll need to add this exact tag without the quotes. To add a tag just type the words in the tags box, no \# sign needed. Spaces are allowed, hit enter to complete the tag. I highly recommend tagging all notes so you can find them later. You can use your own tags to organize your notes. After this assignment you can use whatever tags you want. I'll see all of your comments under the group listing as lng as they are posted to the group.


**_Step six, save note to group:_** This makes your note visible to everyone in the group and nobody else. Everyone in the group will be also able to respond to this note.

**_Step seven, go to your Hypothes.is page to verify that you did it right:_** Not strictly necessary for other note taking, but do this now so you can see what's there. This is your collection of notes which can be filtered by tags, groups, etc. To get there click the person icon in the Hyothes.is tool and then your user name. That takes you to your Hypothes.is page. You'll have to do two comments every week, for a total of 30 all semester so that is a good place to go to keep yourself on target.

