# Animals and Ethics

**_The history of ethics_** might be looked at a history of the gradual expansion of ethical consideration. Tribal loyalties are replaced by national loyalties, and eventually loyalties to all of humanity; exclusion of women and people in minority groups are replaced by universal rights for all human beings regardless of race or gender. Some philosophers insist that this "expanding circle" of ethics has not quite expanded as far as it should even with universal human rights. At present the majority of human beings act as if the circle of ethical consideration stops at the border of the human species, as if no non-human animals deserve true ethical consideration. Hence we keep certain non-human animals as pets, kill them for food and sport, and perform countless experiments on them in labs without even wondering whether this violates ethical rules that we should pay attention to. In this section we are going to examine a number of arguments concerning the proposed expansion of ethics to include granting at least some animals moral consideration. Note that *moral consideration* does not mean the same thing as *moral rights*, and that although some philosophers, most notably Tom Regan insist that some animals be granted rights, not all who defend granting animals moral consideration follow Regan in this.

**_Before roughly two hundred years ago,_** humans for the most part assumed what I'd like to call the "dogma of difference." This is the idea that whatever our relationship to animals may be, it is the differences between 
us and them that should be emphasized, not the (mostly superficial) similarities. In the *Old Testament*, for example, the story is told of how God created animals separately than human beings and grated us dominion over all of the other animals and plants on the earth, to use as we see fit. The differences between humans and animals according to this story are that we are the *ends* of creation, and animals are just the *means* that we can and should use for our benefit. Likewise, according to this tradition, it is humans alone who have souls, and thus we are in a unique position to control nature, while animals as a part of non-human nature are subject to our control.

**_The modern philosopher Rene Descartes_** took the Christian idea that animals have no souls to its logical conclusion when he suggested that animals have much more in common with inanimate machines, such as clocks, than they do with human beings. This is because animals have only bodies, the movements of which are subject, according to the scientific perspective Descartes helped to create, to entirely mechanical explanations. If animals have no souls, then they also lack what comes from having a soul -- inner experience, experience of pleasure and pain, experience of one's own thoughts, fears and desires. Since, as Descartes argued, according to the tradition going back at least to the Old Testament, animals do not have souls, they are thus incapable of experiencing anything, not even pleasure or pain. How then do we explain why it is that animals appear to experience things, like pain for example? Well, when a dog makes noises as a result of being injured, this would have to be the same kind of thing that your alarm clock does when it is set to go off at a certain time -- it makes noises for purely mechanical reasons. Since both clocks and dogs lack souls their noises are not experienced "from inside" by anyone or anything -- there is "nobody home" inside a dog or a clock. The ethical implications of this are that there are no ethical implications -- however we treat animals is OK, since not only did God give us dominion over animals, they do not even really experience the kinds of things that we experience when we ask others not to harm us or set back our interests.

**_This extreme view _**of the dogma of difference was challenged somewhat, though not entirely, by later philosophers, like Kant. Kant believed, as we have seen that the basis for genuine moral relations with other persons is their ability to understand what it means to respect another being. This requires rationality, the ability to understand the abstract idea of respect. Since, in his view, animals lack this ability, they neither owe us nor are owed respect. In terms of Kant's distinction between persons and things, animals fall entirely on the side of things, possessing merely instrumental value. However, Kant did recognize that certain animal behaviors bear an analogy with human behavior -- hence a dog cries out in pain when beaten. Whether or not the animal is "really" feeling pain when a person beats it does not matter as much as the fact that it seems to. Kant reasons that if it seems to us that animals feel pain when mistreated this may serve to harden us to human suffering, and this would be an unwelcome outcome. Kant clearly endorses the dogma of difference since it is only his belief that mistreating animals will have bad effects on human relations to other humans that underlies his view that we should not abuse animals too much.

**_Since the nineteenth century however,_** the development of the science of biology has fundamentally challenged one of the major supports of the dogma of difference by challenging the strict separation between animals and humans on scientific grounds. As modern biology has amply demonstrated, we are made of the same basic stuff, the same complex biochemicals organized in the same ways into the same types of cells, tissues and organs as other animals. Further, as is now completely accepted by biology, we are related to all other living things, from the lowliest fungus on up the scale of complexity to the most complex mammals -- we are all part of a single, vast family tree going back to the first appearance of life on earth some four billion years ago. In addition to these deep similarities between all life forms, there is much evidence that human behavior is not as different from animals' behavior (especially the behavior of other mammals) as Descartes and others believed. The evidence comes in the form of studies of the physiological basis of human and animal experience and behavior. Although we can never really know from inside what it is like to be a dog or a cow, we do know that dog and cow brains have the same parts that support experiences of pain and pleasure in us. In addition, scientists have spent years documenting the complexities of social organization in such animals as chimpanzees and gorillas and the picture that emerges here is that certain animals are not really that different from humans.

**_Biology, however,_** does not simply point out that we are much more closely related to other living things than we previously suspected. It also provides us with a powerful set of tools for more effectively and efficiently exploiting animals for our purposes. Consider the modern "factory farm" in which biology is put to work to maximize the yield from animals for human purposes. Modern methods of animal production involve:

- Living conditions designed for maximum efficiency in feeding and  growth -- cows in a feedlot get fat quicker with the use of less land than cows on the open range; pigs are bred for lean and consistent flesh produced in the shortest period of time.
- Scientifically engineered diets designed to make them grow as quickly as possible -- cows raised for meat are feed high protein diets to give their flesh a rich fat content that us humans have a taste for; animal feed is mixed with growth promoting and disease inhibiting antibiotics.
- Special methods employed for particular results or to address problems caused by intensive production: chickens have their beaks partially cut off to keep them from killing each other when they attack each other in overcrowded coops; veal calves are kept from moving to keep their flesh tender; pigs are increasingly raised indoors because decades of being bred for rapid meat production makes them incapable of surviving in their natural habitat, outside they would be quickly killed by cold and disease.
- Use of hormones to increase yield: milk cows are injected with hormones so they produce more milk and their feed is supplemented with animal protein (ground up cows, chickens, horses, pigs, etc.) to  enable them to produce the extra milk.

**_All of this is made possible_** by our increased understanding of the way animals work. So the ironic result of biology is that it supports the idea that animals are not that different from us and so maybe might deserve more moral consideration, and at the same time enables us to make much more efficient and ruthless use of animals as meat and milk production machines. As a result of biology, animals, paradoxically, appear both more like persons that have moral value and more like things that have only instrumental value. Rather than solving the problem of the moral status of animals, modern biology presents us with a dilemma: our knowledge of the way animals work gives us both more reason to respect them and more opportunity to exploit them.

## Defending The Status Quo

**_There are three ways of responding_** to this dilemma. The simplest and most obvious in a sense is simply to ignore the one side of the dilemma, the side that suggests that animals may deserve moral consideration in view of their similarity to us. This is the approach we can call the "status quo approach" to non-human animals. We will examine it first and then move on to consider the other two possibilities, one recommending reform of our relations with other animals and one advocating a revolutionary overhaul of these relations.

### The top of the heap{-}

**_How can the status quo be defended?_** The usual answer is with reference to the old ideas of human dominion over nature -- since we are on the top of the heap, what we say goes. 

::::{.center data-latex=""}
:::{.argument data-latex=""}

Humans are more powerful than any other creature on earth.\
Because of this we have the ultimate say over how other animals are to be treated.\

Thus whatever we decide to do is the correct thing to do as far as non-human animals are concerned.

:::
::::

**_However popular this view may be,_** it is deeply flawed, because it commits an obvious fallacy, the fallacy of appeal to force. The fact that we have the power to determine the rules does not imply that whatever rules we establish are good rules. As we have seen throughout the semester the fact that someone has power or authority does not at all establish that whatever they do is the morally correct thing to do. Power can be abused or it can be used to do good, so power itself does not imply a moral license to do whatever one can and get away with it.

### Human needs {-}

**_Until we provide some reasons_** why we should be permitted to use animals for food, research and entertainment without any moral consideration, we will not have a leg to stand on. Now the most obvious reason we might have for our current methods of treatment of animals appeals to human needs. According to this line of reasoning, since we *need* to use animals we should be permitted to do whatever provides us with the maximum benefit.

::::{.center data-latex=""}
:::{.argument data-latex=""}

We need to use non-human animals for food, research and entertainment purposes.\
The satisfaction of these needs overrides the interests of animals in not being used by us.\

So we need not change the way we treat non-human animals.

:::
::::

**_There are a number of objections_** to this argument that we might consider, but I will focus on just two. First, assuming that it is true that we need to use animals for food, research and entertainment, it plainly does not follow that they thus deserve *no* moral consideration whatsoever. The fact that I may need something does not imply that there are no moral restrictions on how I might go about satisfying that need. After all, I certainly need money in order to survive in the modern world, but there are still plenty of moral restrictions on how I am allowed to go about getting money. I can only satisfy my needs in ways that do not interfere with my moral responsibility to respect other people's rights and interests. Thus even if we need to eat animals, modern factory farms may turn out to be unacceptable ways of satisfying those needs. The fact that this issue has not yet been addressed does not imply that anything goes as far as non-human animals are concerned.

**_Second, we may object_** to this argument by challenging the idea that we need to use animals at all for the purposes mentioned. As the existence of millions of strict vegetarians worldwide demonstrates, humans do not *need* to eat meat. We are "naturally" omnivorous, but can easily survive, some argue more healthily, without the consumption of animal flesh. So our eating of meat is not a need but a *preference*. Likewise with our other uses of animals, we certainly do not *need* to use animals as companions, as curiosities in zoos, as targets of sport hunting, or even as research subjects. The last of these is sure to arose skepticism -- don't we really need to use animals as test subjects for urgent medical research that saves human lives? The answer is no -- we may strongly prefer to use animals for testing drugs, because research protocols are established, and because it is cheap and easy to experiment on animals. But there are also many viable alternatives, some of which are gaining ground as more reliable and ultimately more cost-effective, such as computer modeling of the immune system as a way of testing drugs, or the use of tissue cultures, which require only small samples of animal cells raised in petri dishes. Thus this argument, which may have at first seemed to be a good way of defending currently popular practices does not succeed in establishing what it claims to establish.

### The benefits of our use of animals {-}

**_Granted that we do not,_** strictly speaking, *need* to use animals as we do, we may still argue that the benefits of our uses of animals are a sufficient justification for things to continue as they currently are done.

::::{.center data-latex=""}
:::{.argument data-latex=""}

It is beneficial for us to use non-human animals for food, research and entertainment purposes.\
Imposing ethical limits on the way we treat animals would increase our costs.\

So, on simple utilitarian grounds, we should not change the way we treat non-human animals.

:::
::::

**_Well what about this argument?_** Once again it seems promising at first, but a little critical prodding will soon show that it makes a really big assumption. That is, it assumes that animals do not count in our utilitarian assessments of costs and benefits. Benefits here are benefits to us and costs are likewise costs to us according to this argument. But it seems clear that animals are being asked to bear the burden of being eaten by us, used as research subjects and so on, without the slightest consideration of their benefits and costs. Now we have not yet seen any reasons why we should take animals' costs and benefits into account, but this argument cannot possibly establish that we need not do this, since it assumes from the start that animals' costs and benefits do not count. So at best it remains neutral as far as a defense of the status quo -- if animals do not count morally, we should be permitted to use them, and at worst it simply begs the question -- it argues that animals do not count on the assumption that, well, they do not count.

## Humane Reform

**_So far the status quo_** seems kind of tough to defend, so what about the alternatives? We now turn to attempts to defend a kind of moderate reform that would enable us, in theory at least, to avoid the worst excesses of the status quo while stopping short of granting to non-human animals any kind of real moral consideration. This is the approach that is roughly equivalent to that followed by such organizations as the American Society for the Prevention of Cruelty to Animals and the Humane Society, so I call it the "Humane Reform" approach. The first argument to consider here was developed by Kant.

### Kant's argument {-}

**_Recall that in Kant's view_** morality is a relation of strict equality based on the rational recognition that another counts just as much as I do. Even if we are not really strictly equal with each other, our ability to grasp and apply the ideal of moral equality requires us to act as if we really were equal with other moral agents. This implies a set of rights as well as a set of responsibilities -- each of us moral adults deserves absolute respect from other moral agents as well as owing them absolute respect. Well what about non-human animals?

::::{.center data-latex=""}
:::{.argument data-latex=""}

We can have no direct duties to non-human animals since that would require them to be capable of acting out of duty towards us as well.\
But, some animals are like us, so our mistreatment of them will lead us to be insensitive to human suffering and thus will encourage immorality.\

Thus we have indirect duties to treat animals well.

:::
::::

**_This argument_** makes two important claims -- one that we can have no direct duties to animals since they lack the ability to treat us with genuine moral respect; and two, that our mistreatment of animals leads us to mistreat humans. Let us examine the second of these first. Is it true that abusing animals leads humans to abuse people? This treads dangerously close to the false cause fallacy -- even if someone who abuses animals may also lack concern for humans this correlation does not imply causation. Perhaps people who abuse animals are *also* indifferent to human suffering out of a general lack of compassion. As far as the first claim goes, on the other hand, this criterion for genuine moral consideration will soon get us into hot water, so we will hold off on a definite answer to the question of the solidity of this argument.

### Identifying with animals {-}

**_Kant does, however,_** make a pretty obvious point -- that some people are more compassionate towards animals and humans than others. We are clearly capable of forming bonds of sympathy with some non-human animals. This is the basis for the next argument.

::::{.center data-latex=""}
:::{.argument data-latex=""}

Some animals are similar enough to us that we can form genuine bonds of sympathy with them.\
Respecting these emotional attachments that humans form with animals is important.\

So, it is in our own interests to treat animals with compassion and kindness.

:::
::::

**_This reformist argument_** is a good example of we might call "anthropocentric" (literally "human-centered") ethics. It is because of the value we humans get from identifying with certain animals that these animals are considered to count at all. No this may seem like a safe middle ground to occupy -- humans get to remain the sole objects of direct moral concern (and thus we can continue to eat and experiment on those animals with which we do not sympathize) and yet we also admit that some animals seem to count for more than this. Well, it is exactly this attempt to have it all, to have our pets and eat them too, to paraphrase the famous proverb, that causes problems for this line of reasoning. After all it seems kind of arbitrary that we would judge animals depending upon whether or not we think that they are cute, or cuddly or otherwise worthy of our attention and affection. Are piglets or veal calves any less cute than puppies? That seems to be too much a subjective judgment of culturally biased prejudice to say so, and yet based on such judgments many people would be horrified if they were to discover that the veal cutlet they are dining on was in fact a dog cutlet. In other words, reducing ethical considerability to something as fickle as our ability to judge some other animals as cute seems to make nonsense out of moral judgment. Isn't there a more rational basis for ethical judgment? 

**_The revolutionaries think_** that there is and that this rational basis for ethical judgment forces us to conclude that some non-human clearly animals qualify as objects of genuine, direct moral concern. It is to their arguments that we know turn.

## Genuine Moral Consideration

### Animal Welfare {-}

**_As long ago_** as the late 18th century the British Utilitarian philosopher Jeremy Bentham claimed that animals deserve moral consideration to the extent that they can feel pain. He was in fact simply following the logic of the utilitarian view of ethics in making this claim. Recall that utilitarians measure the moral worth of an act by the amount of good it does for all affected by it. This good, in Bentham's view, can be measured in the amount of pleasure that results for those affected. But if pleasure is the sole measure of what is good in an action, why restrict this to human pleasure? Aren't at least certain animals also capable of feeling pleasure and pain? Shouldn't this also be taken into account when we are figuring out the consequences of our actions? Bentham thought that there really was no good reason to think that some creatures' pleasures and pains have moral worth and others' do not. If it is pleasure that makes something good, how could we restrict it only to the pleasure experienced by us, why not also include the pleasure experienced by whoever or whatever is capable of feeling pleasure? So in the name of interspecies democracy Bentham suggested the revolutionary idea that animals should be considered apart from whether or not our decisions regarding them had good or bad effects on us alone. More recently Bentham's position has been revived by the Australian philosopher Peter Singer, and this view represents one wing of the contemporary animal rights movement. Singer's argument can be summed up as follows.

::::{.center data-latex=""}
:::{.argument data-latex=""}

Pleasure and pain are morally significant -- ethical action is that which maximizes pleasure and minimizes pain for all who are affected.\
Some animals can experience pleasure and pain.\

So, we should act in such a way that maximizes pleasure and minimizes pain for humans as well as for those animals affected by our actions.

:::
::::

**_There a couple of points_** worth mentioning here. First Singer is just following out the logic of utilitarianism -- if your pain matters just as much as mine does this can only be because of the nature of pain itself, not the identity of the being who is experiencing pain. If animals are also capable of experiencing pain then it seems that species membership is not crucial for deciding whether you count or not, what counts is the degree to which you can experience pain and pleasure. Second, this view does not imply that humans and animals count the same. Instead it only claims that if you are capable of experiencing pleasure and pain to the same degree then you count the same. So the arguably less intense or less sophisticated sort of pleasure and suffering that birds can experience (they lack the kind of heightened psychological experiences that we humans experience) means that if we were forced to kill a chicken or of a human being we would have to kill the chicken. And finally this position, does not entail that it is simply wrong to kill animals or use them for research. Instead it simply says -- since animal suffering make a moral difference we are obliged to minimize surplus suffering, suffering that is not used as a means to get greater pleasure for all creatures involved than would have been the case without that suffering.

### Animal rights {-}

**_Utilitarian arguments alone cannot_** possibly be the basis for objecting to all uses of animals by humans that are currently the norm. For as we saw when we discussed utilitarianism, one of the big problems faced by utilitarians is that they recognize no concept of rights -- all they are interested in is the total payoff in happiness resulting from our actions. There are, nevertheless, advocates of the idea that animals literally should be considered as having rights.

**_This position_** was first articulated by the American philosopher Tom Regan. Dissatisfied with the unprincipled nature of utilitarian arguments (any kind of action would be acceptable to utilitarians as long as the balance of pleasure and pain were right in the end), Regan argues that animals can and should be granted more than just consideration, they should be granted rights as well. 

::::{.center data-latex=""}
:::{.argument data-latex=""}

It is our cognitive abilities that are the basis of our having rights.\
Humans and animals overlap in terms of cognitive abilities.\

So, either all humans and some animals should have rights, or only some humans but no animals should have them.

:::
::::

**_There are two sides_** to this argument. The first, negative side, suggests that there is no workable way of restricting the idea of rights to humans, without either making the criterion of application so broad that it includes some animals or so narrow that it excludes some humans. That is, if we decide that humans deserve rights because they have a sense of the significance of their own lives, they experience pleasure, pain, the feelings of success and frustration, and have the possibility of running their own lives -- shouldn't this also apply to certain animals, who arguably experience their own lives and are frustrated by not being able to do as they want? If on the other hand we set as a criterion for having rights some more narrowly defined feature of human experience, like the ability to be rational and use language to express ourselves, doesn't this end up excluding some humans from moral consideration? Not all humans are fully rational -- young children are not yet rational, and the mentally retarded never will be -- but this seems no reason not to grant them at least some rights. In other words Regan points out a dilemma with the concept of rights -- we can either define the criterion for granting rights broadly, in which case certain animals seem to qualify, or narrowly in which case certain human do not seem to  qualify as rights bearers. Regan is clearly in favor of including animals in the sphere of those who get rights, and he points out that those who would resist this move would have to also accept that certain humans, those who through mental handicaps or just as a result of being not fully developed lack rationality, should not have rights either.

**_The second, positive side_** of Regan's argument takes over from here -- since animals share something significant with humans, the capacity to experience their own lives as truly their own, why not grant them full moral consideration? After all, if the reason humans deserve rights is because each of us has the capacity to experience the world from our own unique perspective, and that is what is valuable about each human being, isn't it just human chauvinism to insist that no other animals have anything like this ability of ours?


