# Appendix 1: Using Hypothes.is {- #appendix-1}

#### 1. What is it? {-}

It's an online annotation tool. It lets you take notes in the margins of any web page, highlight text, and make page notes, which are comments on the whole of a web page. You also view and respond to other people's comments and notes in some cases. 

- These notes are yours to keep or delete and nobody can read them unless you allow it.
  - They can be made *public* so that any other user of Hypothes.is can see them and respond to them.
  - They can be *private* so only you can see them.
  - They can be *shared with a group* so that only members of that group can see or respond to them.

- They can (and should) be organized by key words (tags) so that you can keep track of all of your notes and the pages you have taken notes on for your research, or for personal use.

- You can use it for your other classes too. All of your notes will be available for you to see organized by tags, pages and groups on the Hypothes.is website.

#### 2. Sounds awesome, but what's the catch?  {-}

There is none. Hypothes.is is run by a non-profit on a mission to encourage note taking and discussion on the web. They are most likely people who read books and write stuff in the margins. You know the type. You don't want to buy used books from them.

This is not a tool for collecting data about you and selling it to advertisers -- they respect privacy and you can read [the Hypothes.is privacy policy here](https://web.hypothes.is/privacy/). It is a free service. This system is supported by grants and by institutions that sign up for paid versions for their own uses. It is free for use by educators and students. You will need to register, but all you will need to do this is provide an email address so they can verify that you are not a spambot. 

Please read the [privacy policy](https://web.hypothes.is/privacy/), [terms of service](https://web.hypothes.is/terms-of-service/) and [community guidelines](https://web.hypothes.is/community-guidelines/) for more information if you like.

#### 3. How to use it. {-}

- There is a Chrome extension for those of you using the Chrome browser. If you install this extension you'll open it by clicking on a symbol on the top bar of your browser.

- There is a special kind of bookmark called a "bookmarklet" that you can save for use in your browser. That creates a link that you can just click  anytime you want to take notes on a page you are reading. If you don't use Chrome this will be what you want. It works on Firefox which is a more private and secure browser than Chrome if you are interested in privacy. 


:::{.note data-latex="" .infobox}

**Special note for using on a phone:**  All you have to do is copy the web address of the page you want to annotate and then [go to this page](https://via.hypothes.is/) and paste it in the box. That runs the page through the Hypothes.is server and let's you add your own notes.

:::

#### 4. Getting started {-}

- Go to the Hypothes.is ["Start Here" page](https://web.hypothes.is/start/) and follow the instructions.

- You'll have to register and either get the Chrome extension or save the bookmarklet. It's simple. **Please pick a username that makes it easy for me to figure out who you are for grading purposes.** "JohnDoe" or "JDoe" is good, "jr435d" is not so good. If you don't like putting your real name on the web, that's OK, but for this it's safe since as long as you are only posting to the special group created for this course, since nobody will see it but other members of the group.

- Next you should join the private group listed on the course web page. Once you do that you are ready to start commenting on any webpage you like.


```{asis, echo=identical(knitr:::pandoc_to(), 'html')}

#### A short video tutorial {-}

<iframe width="560" height="315" src="https://www.youtube.com/embed/e235JwmmEcQ" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>


```
